# Generated by Django 5.0.1 on 2024-04-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_favoris_favoris'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_supprimer',
            field=models.BooleanField(default=False),
        ),
    ]
