# Generated by Django 5.0.1 on 2024-04-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_is_supprimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_supprimer',
            field=models.BooleanField(default=True),
        ),
    ]
