# Generated by Django 5.0.1 on 2024-04-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_is_supprimer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_supprimer',
        ),
    ]
