# Generated by Django 5.0.1 on 2024-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_is_supprimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoris',
            name='is_favoris',
            field=models.BooleanField(default=True),
        ),
    ]
