# Generated by Django 5.0.1 on 2024-04-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_favoris_is_favoris'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
    ]
