# Generated by Django 5.0.1 on 2024-05-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_consultation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FileField(default='1.jpg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.FileField(default='1.jpg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.FileField(default='1.jpg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.FileField(default='1.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='1.jpg', null=True, upload_to='images/'),
        ),
    ]
