# Generated by Django 5.0.1 on 2024-05-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_image2_product_image3_product_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='photo',
            field=models.FileField(null=True, upload_to='photo_user'),
        ),
    ]
