# Generated by Django 5.0.1 on 2024-05-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_profil_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(null=True, upload_to='image_categorie/'),
        ),
    ]
